version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passpass
      - MYSQL_DATABASE=achatApp
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  spring_app:
    image: chilliga/ahmedmezni-5bi3-achat
    restart: on-failure
    container_name: achatApp
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatApp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: passpass
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    stdin_open: true
    tty: true

volumes:
  mysql_data: