version: "2.21"

services:
  mysqldb:
    image: mysql:8.0.31
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    image: application
    ports:
      - 8085:8085
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: